from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = PROJECT_ROOT / "Data"
RAW_DIR = DATA_DIR / "Raw"
PARAMETERS_DIR = DATA_DIR / "parameters"
OUTPUT_DIR = DATA_DIR / "output"
QUALITY_DIR = DATA_DIR / "quality"

RAW_FILES = {
    "E_CUSTOMER": RAW_DIR / "E_CUSTOMER.csv",
    "E_CONTRAT_CREDIT": RAW_DIR / "E_CONTRAT_CREDIT.csv",
    "E_ENCOURS": RAW_DIR / "E_ENCOURS.csv",
}

PARAMETER_FILES = {
    "P_CODE_DOC_BCT": PARAMETERS_DIR / "P_CODE_DOC_BCT.csv",
    "P_FORME_CREDIT_BCT": PARAMETERS_DIR / "P_FORME_CREDIT_BCT.csv",
    "P_SEGMENT_FORCE": PARAMETERS_DIR / "P_SEGMENT_FORCE.csv",
    "P_SEGMENT_RISQ_CONDITION": PARAMETERS_DIR / "P_SEGMENT_RISQ_CONDITION.csv",
    "P_SEGMENT_RISQ_REGLE": PARAMETERS_DIR / "P_SEGMENT_RISQ_REGLE.csv",
}